load("@player-ui_rules_player//kotlin:build.bzl", "kt_jvm_library_and_test")
kt_jvm_library_and_test(
  name = "lib",
  main_srcs = ["lib.kt"],
  test_srcs = ["lib.test.kt"],
  test_package = "com.intuit.bazel.kotlin"
)
