local_repository(
    name = "player-ui_rules_player",
    path = "../../..",
)

load("@player-ui_rules_player//:workspace.bzl", "deps")
deps()

load("@player-ui_rules_player//:conf.bzl", "kotlin")
kotlin()

load("@io_bazel_rules_kotlin//kotlin:core.bzl", "kt_register_toolchains")
kt_register_toolchains()

load("@player-ui_rules_player//junit5:conf.bzl", "junit5")
junit5()
