load("//android:workspace.bzl", "android")
load("//apple:workspace.bzl", "apple")
load("//bazel:workspace.bzl", "skylib")
load("//cocoapods:workspace.bzl", "cocoapods")
load("//distribution:workspace.bzl", "distribution")
load("//junit5:workspace.bzl", "junit5")
load("//kotlin:workspace.bzl", "kotlin")
load("//maven:workspace.bzl", "maven")
load("//javascript:workspace.bzl", "javascript")

def deps():
    android()
    apple()
    skylib()
    distribution()
    junit5()
    kotlin()
    maven()
    javascript()
    cocoapods()