load("@rules_player//kotlin:defs.bzl", "kt_jvm")

kt_jvm(
    name = "kt_lib",
    main_srcs = ["lib.kt"],
    test_srcs = ["libtest.kt"],
    test_package = "com.intuit.bazel.kotlin",
    test_deps = []
)


