local_repository(
    name = "rules_player",
    path = "../../..",
)

load("@rules_player//kotlin:workspace.bzl", "kotlin_repository")
kotlin_repository(
    remote = "https://github.com/bazelbuild/rules_kotlin.git",
    # pre bzlmod flag in their .bazelrc
    commit = "6e3339770551881f63d657c1f7b8bbdcd3d23c2c",
    shallow_since = "1654891732 -0400"
)

load("@rules_player//kotlin:repository.bzl", "archive")
archive()

load("@rules_player//kotlin:conf.bzl", kotlin_conf = "kotlin")
kotlin_conf()

load("@io_bazel_rules_kotlin//kotlin:core.bzl", "kt_register_toolchains")
kt_register_toolchains()

load("@rules_player//junit5:conf.bzl", junit5 = "junit5")
junit5()
