local_repository(
    name = "rules_player",
    path = "../../..",
)

load("@rules_player//kotlin:workspace.bzl", "kotlin_repository")
kotlin_repository(
    remote = "https://github.com/bazelbuild/rules_kotlin.git",
    branch = "master",
)

load("@rules_player//kotlin:repository.bzl", "archive")
archive()

load("@rules_player//kotlin:conf.bzl", kotlin_conf = "kotlin")
kotlin_conf()

load("@io_bazel_rules_kotlin//kotlin:core.bzl", "kt_register_toolchains")
kt_register_toolchains()

load("@rules_player//junit5:conf.bzl", junit5 = "junit5")
junit5()
