workspace(
    name = "javascript",
    managed_directories = {
        "@npm": ["./node_modules"],
    },
)

local_repository(
    name = "rules_player",
    path = "../../..",
)

load("@rules_player//bazel:workspace.bzl", "skylib")
skylib()

load("@rules_player//javascript:workspace.bzl", deps = "javascript")
deps()

load("@rules_player//javascript:conf.bzl", "javascript")
javascript()

load("@build_bazel_rules_nodejs//:index.bzl", "node_repositories", "yarn_install")

node_repositories(
    node_version = "16.12.0",
    yarn_version = "1.22.17",
)

yarn_install(
    name = "npm",
    package_json = "//:package.json",
    strict_visibility = False,
    yarn_lock = "//:yarn.lock",
)
