workspace(
    name = "javascript",
    managed_directories = {
        "@npm": ["./node_modules"],
    },
)

local_repository(
    name = "rules_player",
    path = "../../..",
)

load("@rules_player//:workspace.bzl", "deps")
deps()

load("@rules_player//:conf.bzl", "javascript", "kotlin")
javascript()

load("@build_bazel_rules_nodejs//:index.bzl", "node_repositories", "yarn_install")

node_repositories(
    node_version = "16.12.0",
    yarn_version = "1.22.17",
)

yarn_install(
    name = "npm",
    package_json = "//:package.json",
    strict_visibility = False,
    yarn_lock = "//:yarn.lock",
)

kotlin()

load("@io_bazel_rules_kotlin//kotlin:core.bzl", "kt_register_toolchains")
kt_register_toolchains()

load("@rules_player//distribution:maven.bzl", "install")
install()
