local_repository(
    name = "player-ui_rules_player",
    path = "../../..",
)

load("@player-ui_rules_player//kotlin:workspace.bzl", "kotlin")
kotlin(
    tag = "v1.5.0",
    sha256 = "12d22a3d9cbcf00f2e2d8f0683ba87d3823cb8c7f6837568dd7e48846e023307",
    baseUrl = "https://github.com/bazelbuild/rules_kotlin/releases/download",
)

load("@player-ui_rules_player//:workspace.bzl", "deps")
deps()

load("@player-ui_rules_player//:conf.bzl", kotlin_conf = "kotlin")
kotlin_conf()

load("@io_bazel_rules_kotlin//kotlin:core.bzl", "kt_register_toolchains")
kt_register_toolchains()

load("@player-ui_rules_player//junit5:conf.bzl", junit5 = "junit5")
junit5()
