package(default_visibility = ["//visibility:public"])

py_binary(
  name = "convert_ios_test_reports",
  srcs = ["convert_ios_test_reports.py"],
)

exports_files([
    "pod_repo_push.sh",
    "pod_trunk_push.sh"
])